spring:
  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}   # Contraseña o clave de aplicación
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls: true

