spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tp_spring_grupo8
    username: root
    password: Mica345708.

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

  security:
    user:
      name: clienteregistrado8@gmail.com
      password: grupo8

  mail:
    host: smtp.gmail.com
    port: 587
    username: clienteregistrado8@gmail.com
    password: mnkxeubvzlnzshvt  # Contraseña o clave de aplicación
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls: true

